apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: swing-detector

resources:
- ../../base
- ingress.yaml
- middleware.yaml
- postgres-route.yaml

images:
- name: ghcr.io/6cclab/swing-detector-admin
  newName: ghcr.io/6cclab/swing-detector-admin
  newTag: f771b40ebbbe528eb85b18a95021c8d088bb96f6
- name: ghcr.io/6cclab/swing-detector-api
  newName: ghcr.io/6cclab/swing-detector-api
  newTag: 06f62196758463e50f6025156377bd16894d3caa
- name: ghcr.io/6cclab/swing-detector-worker
  newName: ghcr.io/6cclab/swing-detector-worker
  newTag: 6a98d445fabc8e645c5bb1b8a9692c365039a743
