apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: swing-detector

resources:
- ../../base
- ingress.yaml
- middleware.yaml
- postgres-route.yaml

images:
- name: ghcr.io/6cclab/swing-detector-admin
  newName: ghcr.io/6cclab/swing-detector-admin
  newTag: b9717a7c72ec5c769b342bdbcd1e1b8fa6a3798c
- name: ghcr.io/6cclab/swing-detector-api
  newName: ghcr.io/6cclab/swing-detector-api
  newTag: b9717a7c72ec5c769b342bdbcd1e1b8fa6a3798c
- name: ghcr.io/6cclab/swing-detector-worker
  newName: ghcr.io/6cclab/swing-detector-worker
  newTag: 6a98d445fabc8e645c5bb1b8a9692c365039a743
