apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: swing-detector

resources:
- ../../base
- ingress.yaml
- middleware.yaml

images:
- name: ghcr.io/6cclab/swing-detector-api
  newName: ghcr.io/6cclab/swing-detector-api
  newTag: 9d8460410ddc1fbb8262545861b71c42f7f616e8
- name: ghcr.io/6cclab/swing-detector-worker
  newName: ghcr.io/6cclab/swing-detector-worker
  newTag: 9d8460410ddc1fbb8262545861b71c42f7f616e8
