---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: swing-postgres
spec:
  entryPoints:
    - postgres
  routes:
    - match: HostSNI(`*`)
      services:
        - name: swing-detector-postgres
          port: 5432
