apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: swing-detector
spec:
  resyncInterval: 60
  authentication:
    kubernetesAuth:
      identityId: ccebb465-42d4-4b19-9dac-9eec7a9e5613
      serviceAccountRef:
        name: infisical-auth
      secretsScope:
        projectId: d5b5e6bf-5c59-4ea3-ae8f-7d72ac65438d
        envSlug: dev
        secretsPath: /
        recursive: true
  managedSecretReference:
    secretName: swing-detector-secrets
    creationPolicy: Owner
