apiVersion: v1
kind: Service
metadata:
  name: swing-detector-api
  labels:
    app.kubernetes.io/name: swing-detector-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app.kubernetes.io/name: swing-detector-api
---
apiVersion: v1
kind: Service
metadata:
  name: swing-detector-admin
  labels:
    app.kubernetes.io/name: swing-detector-admin
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: swing-detector-admin
